layout_spectrum: 0.042804580181468245
typography_spectrum: 0.9976575503744517
color:
  brandStrength: 0.8069363382552741
  lightness: 0.3395243976972444
  saturation: 0.2273560177519143
  rhythmicContrast: 0.4591536902721123
  brandColors:
    - '#4F4388'
    - '#FFFFFF'
    - '#9D93BB'
    - '#DED6E2'
    - '#696086'
name: '#AgentShark'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/15a58cbb-9317-408d-992b-5dc689b2d8fd.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/15a58cbb-9317-408d-992b-5dc689b2d8fd.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: external
    url: 'http://www.AgentShark.us'
    label: Click To view Homes For Sale
  - type: contact
    url: 'tel:5167788869'
    label: Call 5167788869
title: '#AgentShark'
description: Joseph Shark Perez- Licensed Real Estate Sales Person
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b76bab04-b288-4da4-8a99-b67e9aadfed9.jpg
content_rating:
  adult: false
author:
  name: Joseph Shark Perez
  url: 'http://www.JoeShark.com'
url: 'http://joeshark.com'
