layout_spectrum: 0.7210003176619215
typography_spectrum: 0.7665416107968529
color:
  brandColors:
    - '#85C226'
    - '#9B9B9B'
    - '#006C67'
    - '#000000'
    - '#808000'
  brandStrength: 0.4460370428727405
  lightness: 0.7502915712562159
  saturation: 0.901271002967427
  rhythmicContrast: 0.5286752874085145
name: '#AgentShark'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d13516a9-7bc3-4403-959c-6cb6ab95812b.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d772b63f-6380-43b4-b23f-8cbbc43e3817.png
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/a6dc59eb-24fb-4cde-a026-f970a9ab2ca4.jpg
purpose:
  - type: contact
    label: Call 5167788869
    url: 'tel:5167788869'
  - type: external
    url: 'http://www.MrHome.realty'
    label: View Homes For Sale Here
title: '#MrHomerealestate'
description: Joseph Shark Perez- Licensed Real Estate Sales Person
author:
  name: Joseph Shark Perez
  url: 'http://www.JoeShark.com'
content_rating:
  adult: false
navigation:
  - name: About Us
    id: d79d983e-236b-4c4f-b967-7ecd5e5e20dd
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/65e5c82c-8962-41e5-ba2a-4db16155b20c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/65e5c82c-8962-41e5-ba2a-4db16155b20c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4da661db-81e7-4279-94d3-fc12a40b2988.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4da661db-81e7-4279-94d3-fc12a40b2988.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2dec3f90-de11-4493-bfd6-6fb8f6bf63bc.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2dec3f90-de11-4493-bfd6-6fb8f6bf63bc.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
